global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-backend'
    static_configs:
      - targets: ['backend:9100']  # Backend container must expose metrics on port 9100
